---
title: "Conference Abstracts"
---

###__2019__

Trask, S., Pullins, S.E., & Helmstetter, F.J. The role of the retrosplenial subregions in trace fear acquisition and recall. Presented at the annual Neuroscience Symposium in March, 2019 (Milwaukee, WI).

###__2018__

Ferrara, N.C., Cullen, P.K., Pullins, S.E., Trask, S., & Helmstetter, F.J. Inhibition of thalamic terminals in the amygdala may facilitate extinction learning. Poster presented at the Society for Neuroscience annual meeting in November, 2018 (San Diego, CA).

Ferrara, N.C., Trask, S., Pullins, S.E., Helmstetter, F.J. Contextual novelty encoded by the dorsal hippocampus regulates synaptic destabilization  and memory lability in the amygdala. Poster presented at the Society for Neuroscience annual meeting in November, 2018 (San Diego, CA).

Trask, S., Ferrara, N.C., & Helmstetter, F.J. Optogenetic silencing of the thalamo-amygdala pathway, but not lateral amygdala, results in a long-term decrease in fear expression. Poster presented at the annual meeting of the Pavlovian Society in October, 2018 (Iowa City, IA).

Ferrara, N.C., Cullen, P.K., Pullins, S.E., Trask, S., & Helmstetter, F.J. Inhibition of thalamic terminals in the amygdala may facilitate extinction learning. Poster presented at the annual meeting of the Pavlovian Society in October, 2018 (Iowa City, IA).

Trask, S., Keim, C. L., & Bouton, M. E. Factors that Encourage Generalization from Extinction to Test Reduce Resurgence of an Extinguished Operant Response. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortices differentially affects minimally and extensively trained actions. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

Thrailkill, E. A., Alcala, J., Vidal, P., Trask, S., & Bouton M. E. Can discriminated operants become habits? Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

###__2017__

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortices differentially affects minimally and extensively trained actions. Poster presented at the Society for Neuroscience annual meeting in November, 2017 (Washington D.C.). 

Trask, S., Keim, C. L., & Bouton, M. E. Factors that Encourage Generalization from Extinction to Test Reduce Resurgence of an Extinguished Operant Response. Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Thrailkill, E. A., Trask, S., & Bouton M. E. Can discriminated operants become habits? Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortex respectively affects expression of minimally-trained and extensively-trained goal-directed actions. Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Perry, M. K., Shipman, M. L., Trask, S., & Green, J. T. The role of the cerebellum in goal-directed behavior. Poster presented at the annual symposium for the Summer Neuroscience Undergraduate Research Fellowship in August, 2017 (Burlington, VT).

Trask, S., & Bouton, M. E. (2017). Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Poster presented at the annual meeting of the Society for the Quantitative Analysis of Behavior in May, 2017 (Denver, CO). 

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. (2017). Inactivation of the prelimbic cortex affects an undertrained, but not overtrained, action. Poster presented at the annual University of Vermont Student Research Conference in April, 2017 (Burlington, VT).

Trask, S., & Bouton, M. E. (2017). Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Presented at the annual Dartmouth Neuroscience Symposium in April, 2017 (Hanover, NH). *Selected for 5-minute platform talk presentation.

Trask, S., & Bouton, M. E. (2017). Retrieval cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

Schoenberg, H. L., Seyller, E., Trask, S., Kirshenbaum, A. P., & Toufexis, D. J. (2017). Methamphetamine pre-exposure produces habitual responding to sucrose in female, but not male, rats. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. (2017). Inactivation of the prelimbic cortex attenuates responding of an undertrained by not overtrained action. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

###__2016__

Trask, S., & Bouton, M. E. (2016). Reducing the negative impact of context change on an operant response. Poster presented at the 4th annual Conference for the Vermont Center of Behavior and Health in October, 2016 (Burlington, VT).

Trask, S., & Bouton, M. E. (2016). Reducing the negative impact of context change on an operant response. Poster presented at the annual meeting of the Pavlovian Society in October, 2016 (Jersey City, NJ).

Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. (2016). Inactivation of the prelimbic cortex attenuates responding of an undertrained by not overtrained action. Poster presented at the annual meeting of the Pavlovian Society in September, 2016 (Jersey City, NJ).

Schoenberg, H. L., Seyller, E., Trask, S., Kirshenbaum, A. P., & Toufexis, D. J. (2016). Methamphetamine pre-exposure produces habitual responding to sucrose in female, but not male, rats. Poster presented at the Society for Behavioral Neuroendocrinology annual meeting in August, 2016 (Montreal, QC, Canada).

Dantzler, J. M., Shipman, M. L., Trask, S., Bouton, M. E., & Green, J. T. (2016). Inactivation of the prelimbic cortex attenuates a new action, but not an old action. Poster presented at the annual symposium for the Summer Neuroscience Undergraduate Research Fellowship in August, 2016 (Burlington, VT).

Trask, S., Shipman, M.L., Green, J.T., & Bouton, M.E. (2016). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the Eastern Psychological Association annual conference in March, 2016 (New York, NY).

###__2015__

Shipman, M.L., Trask, S., Green, J. T., & Bouton, M.E. (2015). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the 3rd annual Conference for the Vermont Center of Behavior and Health in October, 2015 (Burlington, VT).

Bouton, M.E., Trask, S., & Carranza-Jasso, R. (2015). Learning not to make the response during operant extinction. Poster presented at the 3rd annual Conference for the Vermont Center of Behavior and Health in October, 2015 (Burlington, VT).

Shipman, M.L., Trask, S., Green, J. T., & Bouton, M.E. (2015). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the annual meeting of the Pavlovian Society in September, 2015 (Portland, OR).

Bouton, M.E., Trask, S., & Carranza-Jasso (2015). Learning not to make the response during operant extinction. Poster presented at the annual meeting of the Pavlovian Society in September, 2015 (Portland, OR).

###__2014__

Carranza-Jasso, R., Trask, S., & Bouton, M.E. (2014). Tests for the acquisition of response inhibition during extinction of discriminated operant behavior. Poster presented at the annual Learning and Memory Meeting in October, 2014 (Mexico City, Mexico).

Trask, S., & Bouton, M.E. (2014). Discriminative role of alternative reinforcement in the inhibition of operant behavior. Poster presented at the 2nd annual Conference for the Vermont Center of Behavior and Health in October, 2014 (Burlington, VT).

Trask, S., & Bouton, M.E. (2014). Discriminative role of the reinforcer in the inhibition of operant behavior. Poster presented at the annual meeting of the Pavlovian Society in September, 2014 (Seattle, WA).

Trask, S., Schepers, S.T., & Bouton, M.E. (2014) Getting rid of resurgence: Implications for contingency management treatments. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2014 (Burlington, VT).

###__2013__

Schepers, S.T., Trask, S., & Bouton, M.E. (2013) Effects of imposing a negative contingency between the first behavior and Phase 2 reinforcement on resurgence after instrumental extinction. Poster presented at the Eastern Psychological Association annual conference in March, 2013 (New York, NY).

###__2012__

Leppla, C.A., Trask, S., & Jasnow, A.M. (2012). Dopamine controls the precision of long-term fear memory. Poster presented at the Society for Neuroscience annual meeting in October, 2012 (New Orleans, LA). 

Cullen, P.K., Trask, S., Dulka, B. N., Riccio, D.C., & Jasnow, A.M. (2012). The role of presynaptic inhibition in the generalization of context memory. Poster presented at the Society for Neuroscience annual meeting in October, 2012 (New Orleans, LA). 

Cullen, P.K., Dulka, B.N., Trask, S., Riccio, D.C., & Jasnow, A.M. (2012). The loss of presynaptic GABAB1A receptors in increased rates of context fear generalization. Poster presented at the Pavlovian Society annual meeting in September, 2012 (Jersey City, NJ). 

Trask, S., Leppla, C.A., Lynch, J.F. III, Cullen, P.K., & Riccio, D.C. (2012). Differences in extinction retention in rats after a short or long delay. Poster presented at the Undergraduate Research Symposium in April, 2012 (Kent, OH).

Leppla, C.A., Trask, S., & Jasnow, A.M. (2012). Dopamine modulates the precision of long term memory. Poster presented at the Undergraduate Research Symposium in April, 2012 (Kent, OH).

Lynch, J.F. III, Latsko, M., Leppla, C.A., Trask, S. & Riccio, D.C. (2012). Forgetting of stimulus attributes after adolescent exposure to nicotine and stress. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

Meduri, J., Dulka, B., Leppla, C., & Trask, S. (2012). Social defeat produces long-term changes in social behavior and specific deficits in fear extinction. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

Cullen, P.K., Trask, S., Leppla, C.A., Dulka, B.N. & Latsko, M. (2012). Bidirectional effects of increasing histone acetylation on extinction learning. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

###__2011__

Trask, S., Cullen, P.K., Gos, K. K., Pickens, L., Fountain, S., & Riccio, D. C. (2011). Adolescent nicotine affects memory for stimulus attributes but not extinction. Poster presented at the annual meeting of the Midwestern Psychological Association in May, 2011 (Chicago, IL).