---
title: "Curriculum Vitae"

output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float: yes
---

###[__Download CV__](pubs/Trask CV.pdf)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
___

#Publications

___

For PDF copies, please email trask@uwm.edu

---

__Trask, S.__, Shipman, M. L., Green, J. T., & Bouton, M. E. (in press). Some factors that restore goal-direction to habitual behavior. Neurobiology of Learning and Memory.

---

Ferrara, N.C., __Trask, S.__, Pullins, S.E., & Helmstetter, F.J. (2019). The dorsal hippocampus mediates synaptic destabilization and memory lability in the amygdala in the absence of contextual novelty. Neurobiology of Learning and Memory, 166, 107089.  https://doi.org/10.1016/j.nlm.2019.107089

---

Ferrara, N.C., Jarome, T.J., Cullen, P.K., Orsi, S.A., Kwapis, J.L., __Trask, S.__, Pullins, S.E., & Helmstetter, F.J. (2019). GluR2 endocytosis-dependent protein degradation in the amygdala mediates memory updating, Scientific Reports, 9, 5180. https://doi.org/10.1038/s41598-019-41526-1

---

__Trask, S.__ (2019). Cues associated with alternative reinforcement can attenuate resurgence of an extinguished free operant response, Learning & Behavior, 47, 66-79. https://doi.org/10.3758/s13420-018-0339-9

---

Thrailkill, E. A., __Trask, S.__, Vidal, P., Alcalá, J. A., & Bouton, M. E. (2018). Stimulus control of actions and habits: A role for reinforcer predictability and attention in the development of habitual behavior, Journal of Experimental Psychology: Animal Learning and Cognition, 44, 370-384. http://dx.doi.org/10.1037/xan0000188

---

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. (2018). Inactivation of the pre- or infralimbic cortices differentially affects minimally and extensively trained actions, Neurobiology of Learning and Memory, 155, 164-172. https://doi.org/10.1016/j.nlm.2018.07.010

---

__Trask, S.__, Keim, C. L., & Bouton, M. E. (2018). Factors that encourage generalization from extinction to test reduce resurgence of an extinguished operant response, Journal of the Experimental Analysis of Behavior, 110, 11-23.  https://doi.org/10.1002/jeab.446

---

__Trask, S.__, & Bouton, M. E. (2018). Retrieval practice after multiple context changes, but not long retention intervals, reduces the impact of a final context change on instrumental behavior. Learning & Behavior, 46, 213-221. https://doi.org/10.3758/s13420-017-0304-z

---

__Trask, S.__ (in press). Free operant. In J. Vonk & T. K. Shackelford (Eds.), Encyclopedia of Animal Learning and Cognition, New York, NY: Springer. https://doi.org/10.1007/978-3-319-47829-6_1251-1

---

 __Trask, S.__, Thrailkill, E. A., & Bouton, M. E. (2017). Occasion setting, inhibition, and the contextual control of extinction in Pavlovian and instrumental (operant) learning. Behavioural Processes, 137, 64-72. http://doi.org/10.1016/j.beproc.2016.10.003
 
---
 
 __Trask, S.__, Shipman, M. L., Green, J. T., & Bouton, M. E. (2017). Inactivation of the Prelimbic Cortex Attenuates Context-Dependent Operant Responding Journal of Neuroscience, 37, 2317-2324. https://doi.org/10.1523/JNEUROSCI.3361-16.2017

---

__Trask, S.__, & Bouton, M. E. (2016). Discriminative properties of the reinforcer can be used to attenuate the renewal of extinguished operant behavior. Learning & Behavior, 44, 151–161. http://doi.org/10.3758/s13420-015-0195-9

---

Bouton, M. E., & __Trask, S.__ (2016). Role of the discriminative properties of the reinforcer in resurgence. Learning & Behavior, 44, 137–150. http://doi.org/10.3758/s13420-015-0197-7

---

Bouton, M. E., __Trask, S.__, & Carranza-Jasso, R. (2016). Learning to inhibit the response during instrumental (operant) extinction. Journal of Experimental Psychology: Animal Learning and Cognition, 42, 246–258. http://doi.org/10.1037/xan0000102

---

__Trask, S.__, Schepers, S. T., & Bouton, M. E. (2015). Context change explains resurgence after the extinction of operant behavior. Mexican Journal of Behavior Analysis, 41, 187–210. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4943327/

---

__Trask, S.__, & Bouton, M. E. (2014). Contextual control of operant behavior: evidence for hierarchical associations in instrumental learning. Learning & Behavior, 42, 281–288. http://doi.org/10.3758/s13420-014-0145-y

---

#Paper Presentations

___

###__2020__

Distinct roles of the anterior and posterior retrosplenial cortices in encoding, but not retrieval, of aversive memory. __Sydney Trask__ and Fred J. Helmstetter. To be presented at the annual meeting for the International Behavioral Neuroscience Society in June, 2020 (Glasgow, Scotland).

Distinct roles of the anterior and posterior retrosplenial cortices in encoding, but not retrieval, of aversive memory. __Sydney Trask__ and Fred J. Helmstetter. To be presented at the annual meeting for the Eastern Psychological Association in March, 2020 (Boston, MA).

###__2019__

The role of the retrosplenial subregions in trace fear recall. __Sydney Trask__ and Fred J. Helmstetter. Presented at the annual Neuroscience Symposium in March, 2019 (Milwaukee, WI).

Role of response error versus expectation error in instrumental extinction. Mark E. Bouton, Eric A. Thrailkill, __Sydney Trask__, and Felipe Alfaro. Presented at the Eastern Psychological Association annual conference in March, 2019 (New York, NY).

###__2018__

Can discriminated operants become habits? Mark E. Bouton, José Alcala, Pedro Vidal, __Sydney Trask__, and Eric A. Thrailkill. Presented at the Gregynog Associative Learning Symposium in April, 2018 (Powys, Wales).

Factors that encourage generalization from extinction to test reduce resurgence of an extinguished operant response. __Sydney Trask__, Christopher L. Keim, & Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2018.

###__2017__

Association formation in operant behavior and prefrontal control of its expression. __Sydney Trask__. Invited presentation. Presented for the University of Maryland - Baltimore Department of Anatomy and Neurobiology in September, 2017 (Baltimore, MD).

Inactivation of the pre- or infralimbic cortices differentially affects minimally and extensively trained actions. Megan Shipman, __Sydney Trask__, Mark E. Bouton, & John T. Green. Presented at the Vermont Summer Summit in June, 2017 (Burlington, VT).

Retrieval cues associated with alternative reinforcement can attenuate resurgence of an extinguished instrumental response. __Sydney Trask__ and Mark E. Bouton. Invited Presentation. Presented at the annual conference for the Association of Behavioral Analysis International in May, 2017 (Denver, CO). 

Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. __Sydney Trask__ and Mark E. Bouton. Presented at the annual meeting of the Society for the Quantitative Analysis of Behavior in May, 2017 (Denver, CO). 

Association formation in operant behavior and prefrontal control of its expression. __Sydney Trask__. Invited presentation. Presented for the University of Wisconsin – Milwaukee Department of Psychology in April, 2017 (Milwaukee, WI).

Inactivation of the prelimbic cortex affects an undertrained, but not overtrained, action. Megan L. Shipman, __Sydney Trask__, Mark E. Bouton, and John T. Green. Presented at the annual Dartmouth Neuroscience Symposium in April, 2017 (Hanover, NH).

Retrieval cues associated with alternative reinforcement can attenuate resurgence of an extinguished operant response. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2017 (Boston, MA).

###__2016__

Learning to inhibit the response during operant extinction. Mark E. Bouton, __Sydney Trask__, and Rodrigo Carranza-Jasso. Presented at the Gregynog Associative Learning Symposium in April, 2016 (Powys, Wales).

Transfer of operant responding to new contexts after training in multiple contexts. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2016 (New York, NY).

Inactivation of the prelimbic cortex attenuates context-dependent excitatory responding. Megan L. Shipman, __Sydney Trask__, John T. Green, and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2016 (Burlington, VT).

Learning to suppress behavior during operant extinction: Implications for cue-exposure therapy. __Sydney Trask__, Rodrigo Carranza-Jasso, and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2016 (Burlington, VT).

###__2015__

Reinforcers associated with extinction can attenuate free-operant renewal. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2015 (Philadelphia, PA).

Response inhibition during extinction in discriminated operant conditioning. Rodrigo Carranza-Jasso, __Sydney Trask__, and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2015 (Philadelphia, PA).

Reducing relapse by presenting a reinforcer associated with behavioral inhibition. __Sydney Trask__ and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2015 (Burlington, VT).

###__2014__

Contextual control of instrumental actions and habits. Mark E. Bouton, __Sydney Trask__, and Eric A. Thrailkill. Presented at the Gregynog Associative Learning Symposium in April, 2014 (Powys, Wales).

Contextual control of operant behavior: Evidence for hierarchical associations in instrumental learning. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2014 (Boston, MA).

###__2013__

Mechanisms of contextual control of instrumental learning. __Sydney Trask__ and Mark E. Bouton. Presented at the Vermont Summer Summit in June, 2013 (Burlington, VT).

###__2012__

Bidirectional effects of increasing histone acetylation on extinction learning. __Sydney Trask__, Patrick K. Cullen, David C. Riccio, and Aaron M. Jasnow. Presented at the TriState Plus Meeting in April, 2012 (Kent, OH).

___

#Conference Abstracts

___

###__2019__

__Trask, S.__, Pullins, S.E., & Helmstetter, F.J. Distinct roles of the anterior and posterior retrosplenial cortices in encoding, but not retrieval, of trace fear memory. Presented at the Society for Neuroscience annual meeting in October, 2019 (Chicago, IL).

Dulka, B.N., __Trask, S.__, & Helmstetter, F.J. The Effects of Aging on Memory and Activity-Driven Protein Degradation. Presented at the annual meeting of the Molecular and Cellular Cognition Society in October, 2019 (Chicago, IL).

__Trask, S.__, Pullins, S.E., & Helmstetter, F.J. Distinct roles of the anterior and posterior retrosplenial cortices in encoding, but not retrieval, of trace fear memory. Presented at the annual meeting of the Pavlovian Society in October, 2019 (Vancouver, BC, Canada).

Dulka, B.N., __Trask, S.__, & Helmstetter, F.J. The Effects of Aging on Memory and Activity-Driven Protein Degradation. Presented at the annual meeting of the Pavlovian Society in October, 2019 (Vancouver, BC, Canada).

__Trask, S.__, Pullins, S.E., & Helmstetter, F.J. The role of the retrosplenial subregions in trace fear acquisition and recall. Presented at the annual Neuroscience Symposium in March, 2019 (Milwaukee, WI).

###__2018__

Ferrara, N.C., Cullen, P.K., Pullins, S.E., __Trask, S.__, & Helmstetter, F.J. Inhibition of thalamic terminals in the amygdala may facilitate extinction learning. Poster presented at the Society for Neuroscience annual meeting in November, 2018 (San Diego, CA).

Ferrara, N.C., __Trask, S.__, Pullins, S.E., Helmstetter, F.J. Contextual novelty encoded by the dorsal hippocampus regulates synaptic destabilization  and memory lability in the amygdala. Poster presented at the Society for Neuroscience annual meeting in November, 2018 (San Diego, CA).

__Trask, S.__, Ferrara, N.C., & Helmstetter, F.J. Optogenetic silencing of the thalamo-amygdala pathway, but not lateral amygdala, results in a long-term decrease in fear expression. Poster presented at the annual meeting of the Pavlovian Society in October, 2018 (Iowa City, IA).

Ferrara, N.C., Cullen, P.K., Pullins, S.E., __Trask, S.__, & Helmstetter, F.J. Inhibition of thalamic terminals in the amygdala may facilitate extinction learning. Poster presented at the annual meeting of the Pavlovian Society in October, 2018 (Iowa City, IA).

__Trask, S.__, Keim, C. L., & Bouton, M. E. Factors that Encourage Generalization from Extinction to Test Reduce Resurgence of an Extinguished Operant Response. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortices differentially affects minimally and extensively trained actions. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

Thrailkill, E. A., Alcala, J., Vidal, P., __Trask, S.__, & Bouton M. E. Can discriminated operants become habits? Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2018 (Burlington, VT).

###__2017__

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortices differentially affects minimally and extensively trained actions. Poster presented at the Society for Neuroscience annual meeting in November, 2017 (Washington D.C.). 

__Trask, S.__, Keim, C. L., & Bouton, M. E. Factors that Encourage Generalization from Extinction to Test Reduce Resurgence of an Extinguished Operant Response. Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Thrailkill, E. A., __Trask, S.__, & Bouton M. E. Can discriminated operants become habits? Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. Inactivation of the prelimbic or infralimbic cortex respectively affects expression of minimally-trained and extensively-trained goal-directed actions. Poster presented at the annual meeting of the Pavlovian Society in October, 2017 (Philadelphia, PA).

Perry, M. K., Shipman, M. L., __Trask, S.__, & Green, J. T. The role of the cerebellum in goal-directed behavior. Poster presented at the annual symposium for the Summer Neuroscience Undergraduate Research Fellowship in August, 2017 (Burlington, VT).

__Trask, S.__, & Bouton, M. E. (2017). Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Poster presented at the annual meeting of the Society for the Quantitative Analysis of Behavior in May, 2017 (Denver, CO). 

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. (2017). Inactivation of the prelimbic cortex affects an undertrained, but not overtrained, action. Poster presented at the annual University of Vermont Student Research Conference in April, 2017 (Burlington, VT).

__Trask, S.__, & Bouton, M. E. (2017). Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Presented at the annual Dartmouth Neuroscience Symposium in April, 2017 (Hanover, NH). *Selected for 5-minute platform talk presentation.

__Trask, S.__, & Bouton, M. E. (2017). Retrieval cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

Schoenberg, H. L., Seyller, E., __Trask, S.__, Kirshenbaum, A. P., & Toufexis, D. J. (2017). Methamphetamine pre-exposure produces habitual responding to sucrose in female, but not male, rats. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. (2017). Inactivation of the prelimbic cortex attenuates responding of an undertrained by not overtrained action. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2017 (Burlington, VT).

###__2016__

__Trask, S.__, & Bouton, M. E. (2016). Reducing the negative impact of context change on an operant response. Poster presented at the 4th annual Conference for the Vermont Center of Behavior and Health in October, 2016 (Burlington, VT).

__Trask, S.__, & Bouton, M. E. (2016). Reducing the negative impact of context change on an operant response. Poster presented at the annual meeting of the Pavlovian Society in October, 2016 (Jersey City, NJ).

Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. (2016). Inactivation of the prelimbic cortex attenuates responding of an undertrained by not overtrained action. Poster presented at the annual meeting of the Pavlovian Society in September, 2016 (Jersey City, NJ).

Schoenberg, H. L., Seyller, E., __Trask, S.__, Kirshenbaum, A. P., & Toufexis, D. J. (2016). Methamphetamine pre-exposure produces habitual responding to sucrose in female, but not male, rats. Poster presented at the Society for Behavioral Neuroendocrinology annual meeting in August, 2016 (Montreal, QC, Canada).

Dantzler, J. M., Shipman, M. L., __Trask, S.__, Bouton, M. E., & Green, J. T. (2016). Inactivation of the prelimbic cortex attenuates a new action, but not an old action. Poster presented at the annual symposium for the Summer Neuroscience Undergraduate Research Fellowship in August, 2016 (Burlington, VT).

__Trask, S.__, Shipman, M.L., Green, J.T., & Bouton, M.E. (2016). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the Eastern Psychological Association annual conference in March, 2016 (New York, NY).

###__2015__

Shipman, M.L., __Trask, S.__, Green, J. T., & Bouton, M.E. (2015). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the 3rd annual Conference for the Vermont Center of Behavior and Health in October, 2015 (Burlington, VT).

Bouton, M.E., __Trask, S.__, & Carranza-Jasso, R. (2015). Learning not to make the response during operant extinction. Poster presented at the 3rd annual Conference for the Vermont Center of Behavior and Health in October, 2015 (Burlington, VT).

Shipman, M.L., __Trask, S.__, Green, J. T., & Bouton, M.E. (2015). Inactivation of the prelimbic cortex attenuates context-dependent excitatory operant responding. Poster presented at the annual meeting of the Pavlovian Society in September, 2015 (Portland, OR).

Bouton, M.E., __Trask, S.__, & Carranza-Jasso (2015). Learning not to make the response during operant extinction. Poster presented at the annual meeting of the Pavlovian Society in September, 2015 (Portland, OR).

###__2014__

Carranza-Jasso, R., __Trask, S.__, & Bouton, M.E. (2014). Tests for the acquisition of response inhibition during extinction of discriminated operant behavior. Poster presented at the annual Learning and Memory Meeting in October, 2014 (Mexico City, Mexico).

__Trask, S.__, & Bouton, M.E. (2014). Discriminative role of alternative reinforcement in the inhibition of operant behavior. Poster presented at the 2nd annual Conference for the Vermont Center of Behavior and Health in October, 2014 (Burlington, VT).

__Trask, S.__, & Bouton, M.E. (2014). Discriminative role of the reinforcer in the inhibition of operant behavior. Poster presented at the annual meeting of the Pavlovian Society in September, 2014 (Seattle, WA).

__Trask, S.__, Schepers, S.T., & Bouton, M.E. (2014) Getting rid of resurgence: Implications for contingency management treatments. Poster presented at the annual conference for Neuroscience, Behavior, and Health in January, 2014 (Burlington, VT).

###__2013__

Schepers, S.T., __Trask, S.__, & Bouton, M.E. (2013) Effects of imposing a negative contingency between the first behavior and Phase 2 reinforcement on resurgence after instrumental extinction. Poster presented at the Eastern Psychological Association annual conference in March, 2013 (New York, NY).

###__2012__

Leppla, C.A., __Trask, S.__, & Jasnow, A.M. (2012). Dopamine controls the precision of long-term fear memory. Poster presented at the Society for Neuroscience annual meeting in October, 2012 (New Orleans, LA). 

Cullen, P.K., __Trask, S.__, Dulka, B. N., Riccio, D.C., & Jasnow, A.M. (2012). The role of presynaptic inhibition in the generalization of context memory. Poster presented at the Society for Neuroscience annual meeting in October, 2012 (New Orleans, LA). 

Cullen, P.K., Dulka, B.N., __Trask, S.__, Riccio, D.C., & Jasnow, A.M. (2012). The loss of presynaptic GABAB1A receptors in increased rates of context fear generalization. Poster presented at the Pavlovian Society annual meeting in September, 2012 (Jersey City, NJ). 

__Trask, S.__, Leppla, C.A., Lynch, J.F. III, Cullen, P.K., & Riccio, D.C. (2012). Differences in extinction retention in rats after a short or long delay. Poster presented at the Undergraduate Research Symposium in April, 2012 (Kent, OH).

Leppla, C.A., __Trask, S.__, & Jasnow, A.M. (2012). Dopamine modulates the precision of long term memory. Poster presented at the Undergraduate Research Symposium in April, 2012 (Kent, OH).

Lynch, J.F. III, Latsko, M., Leppla, C.A., __Trask, S.__ & Riccio, D.C. (2012). Forgetting of stimulus attributes after adolescent exposure to nicotine and stress. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

Meduri, J., Dulka, B., Leppla, C., & __Trask, S.__ (2012). Social defeat produces long-term changes in social behavior and specific deficits in fear extinction. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

Cullen, P.K., __Trask, S.__, Leppla, C.A., Dulka, B.N. & Latsko, M. (2012). Bidirectional effects of increasing histone acetylation on extinction learning. Poster presented at the 27th Annual Graduate Research Symposium in April, 2012 (Kent, OH).

###__2011__

__Trask, S.__, Cullen, P.K., Gos, K. K., Pickens, L., Fountain, S., & Riccio, D. C. (2011). Adolescent nicotine affects memory for stimulus attributes but not extinction. Poster presented at the annual meeting of the Midwestern Psychological Association in May, 2011 (Chicago, IL).

