---
title: "Paper Presentations"
---

###__2019__

The role of the retrosplenial subregions in trace fear recall. __Sydney Trask__ and Fred J. Helmstetter. Presented at the annual Neuroscience Symposium in March, 2019 (Milwaukee, WI).

Role of response error versus expectation error in instrumental extinction. Mark E. Bouton, Eric A. Thrailkill, __Sydney Trask__, and Felipe Alfaro. Presented at the Eastern Psychological Association annual conference in March, 2019 (New York, NY).

###__2018__

Can discriminated operants become habits? Mark E. Bouton, José Alcala, Pedro Vidal, __Sydney Trask__, and Eric A. Thrailkill. Presented at the Gregynog Associative Learning Symposium in April, 2018 (Powys, Wales).

Factors that encourage generalization from extinction to test reduce resurgence of an extinguished operant response. __Sydney Trask__, Christopher L. Keim, & Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2018.

###__2017__

Association formation in operant behavior and prefrontal control of its expression. __Sydney Trask__. Invited presentation. Presented for the University of Maryland - Baltimore Department of Anatomy and Neurobiology in September, 2017 (Baltimore, MD).

Inactivation of the pre- or infralimbic cortices differentially affects minimally and extensively trained actions. Megan Shipman, __Sydney Trask__, Mark E. Bouton, & John T. Green. Presented at the Vermont Summer Summit in June, 2017 (Burlington, VT).

Retrieval cues associated with alternative reinforcement can attenuate resurgence of an extinguished instrumental response. __Sydney Trask__ and Mark E. Bouton. Invited Presentation. Presented at the annual conference for the Association of Behavioral Analysis International in May, 2017 (Denver, CO). 

Cues associated with alternative reinforcement can attenuate reinforcement resurgence of an extinguished instrumental response. __Sydney Trask__ and Mark E. Bouton. Presented at the annual meeting of the Society for the Quantitative Analysis of Behavior in May, 2017 (Denver, CO). 

Association formation in operant behavior and prefrontal control of its expression. __Sydney Trask__. Invited presentation. Presented for the University of Wisconsin – Milwaukee Department of Psychology in April, 2017 (Milwaukee, WI).

Inactivation of the prelimbic cortex affects an undertrained, but not overtrained, action. Megan L. Shipman, __Sydney Trask__, Mark E. Bouton, and John T. Green. Presented at the annual Dartmouth Neuroscience Symposium in April, 2017 (Hanover, NH).

Retrieval cues associated with alternative reinforcement can attenuate resurgence of an extinguished operant response. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2017 (Boston, MA).

###__2016__

Learning to inhibit the response during operant extinction. Mark E. Bouton, __Sydney Trask__, and Rodrigo Carranza-Jasso. Presented at the Gregynog Associative Learning Symposium in April, 2016 (Powys, Wales).

Transfer of operant responding to new contexts after training in multiple contexts. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2016 (New York, NY).

Inactivation of the prelimbic cortex attenuates context-dependent excitatory responding. Megan L. Shipman, __Sydney Trask__, John T. Green, and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2016 (Burlington, VT).

Learning to suppress behavior during operant extinction: Implications for cue-exposure therapy. __Sydney Trask__, Rodrigo Carranza-Jasso, and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2016 (Burlington, VT).

###__2015__

Reinforcers associated with extinction can attenuate free-operant renewal. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2015 (Philadelphia, PA).

Response inhibition during extinction in discriminated operant conditioning. Rodrigo Carranza-Jasso, __Sydney Trask__, and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2015 (Philadelphia, PA).

Reducing relapse by presenting a reinforcer associated with behavioral inhibition. __Sydney Trask__ and Mark E. Bouton. Presented at the annual conference for Neuroscience, Behavior, and Health in January, 2015 (Burlington, VT).

###__2014__

Contextual control of instrumental actions and habits. Mark E. Bouton, __Sydney Trask__, and Eric A. Thrailkill. Presented at the Gregynog Associative Learning Symposium in April, 2014 (Powys, Wales).

Contextual control of operant behavior: Evidence for hierarchical associations in instrumental learning. __Sydney Trask__ and Mark E. Bouton. Presented at the Eastern Psychological Association annual conference in March, 2014 (Boston, MA).

###__2013__

Mechanisms of contextual control of instrumental learning. __Sydney Trask__ and Mark E. Bouton. Presented at the Vermont Summer Summit in June, 2013 (Burlington, VT).

###__2012__

Bidirectional effects of increasing histone acetylation on extinction learning. __Sydney Trask__, Patrick K. Cullen, David C. Riccio, and Aaron M. Jasnow. Presented at the TriState Plus Meeting in April, 2012 (Kent, OH).